### ISSUE TITLE
Download fetch fails via ssl

### ISSUE THREAD

**Issue by RootMale** [mjeanroy/bower-npm-resolver#1]
Download fetch fails via ssl, if you use nexus with ssl cert download.fetch fails with:

{ [Error: write EPROTO]
  code: 'EPROTO',
  errno: 'EPROTO',
  syscall: 'write',
  address: undefined }

The resolver throws:

Stack trace:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at ResolveCache._readPkgMeta (/home/shav/IdeaProjects/default/node_modules/bower/lib/lib/core/ResolveCache.js:337:25)
    at ResolveCache.store (/home/shav/IdeaProjects/default/node_modules/bower/lib/lib/core/ResolveCache.js:108:51)
    at /home/shav/IdeaProjects/default/node_modules/bower/lib/lib/core/PackageRepository.js:188:35
    at _fulfilled (/home/shav/IdeaProjects/default/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/shav/IdeaProjects/default/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/shav/IdeaProjects/default/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /home/shav/IdeaProjects/default/node_modules/bower/lib/node_modules/q/q.js:604:44
    at runSingle (/home/shav/IdeaProjects/default/node_modules/bower/lib/node_modules/q/q.js:137:13)

Console trace:
Error
    at StandardRenderer.error (/home/shav/IdeaProjects/default/node_modules/bower/lib/lib/renderers/StandardRenderer.js:83:37)
    at Logger.<anonymous> (/home/shav/IdeaProjects/default/node_modules/bower/lib/bin/bower:113:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/home/shav/IdeaProjects/default/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/shav/IdeaProjects/default/node_modules/bower/lib/lib/commands/index.js:48:20
    at _rejected (/home/shav/IdeaProjects/default/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /home/shav/IdeaProjects/default/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/home/shav/IdeaProjects/default/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/shav/IdeaProjects/default/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.6
Node version: 4.3.2
OS: Linux 3.16.0-62-generic x64

I guess this custom download.js just not take into account handling of certs, and dont throw informative errors as well. Maybe its possible to use some 3rd party lib for that?

**Comment by mjeanroy** [comment]
Hi,
Thank you for your feedback.

The `download` function use internally the [request](https://github.com/request/request), so it should not be so hard to handle certificates.

The best solution is probably to read the certification configuration from your `bowerrc` file and use it to download the tarball, what do you think ?

**Comment by RootMale** [comment]
Sounds like a plan, however suggest read cert from npm conf, because there is no certs in bowerrc. Is it possible?

**Comment by mjeanroy** [comment]
Hi @RootMale,
Last version of bower-npm-resolver (v0.4.0) use npm to download the package (no more custom download), can you check if you still get the error?

**Comment by mjeanroy** [comment]
@RootMale Closing issue, feel free to re-open if your problem is not fixed with newer version.
