### ISSUE TITLE
"Path must be a string. Received undefined" error during parallel downloads

### ISSUE THREAD

**Issue by nfriend** [mjeanroy/bower-npm-resolver#10]
When several packages are downloaded simultaneously from a private npm registry, it's possible to get a `Path must be a string. Received undefined` error message:

```
bower my-internal-module#0.1.1                 error Path must be a string. Received undefined

Stack trace:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at ResolveCache._readPkgMeta (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\core\ResolveCache.js:337:25)
    at ResolveCache.store (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\core\ResolveCache.js:108:51)
    at C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\core\PackageRepository.js:190:35
    at _fulfilled (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:796:13)
    at C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:604:44
    at runSingle (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:137:13)

Console trace:
Error
    at StandardRenderer.error (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 6.3.1
OS: Windows_NT 10.0.10586 x64
```

I'm using version `0.4.0` of `bower-npm-resolver`.

This is caused when the process is `chdir()`-ed synchronously during the `downloadTarball` function (in `npm-utils.js`).  If a second thread also calls `process.chdir()` before the first has finished running the asynchronous `execPackCommand` function, the tarball ends up in the wrong directory.

**Comment by GabLeRoux** [comment]
I managed to get this error, I wasn't suspecting `bower-npm-resolver` with version `0.4.0` but I actually had the exact same issue.

Example project with a before and after for this exact problem:
https://github.com/GabLeRoux/bower-npm-resolver-inside-docker

:v:
