### ISSUE TITLE
 Could not require module 'npm'

### ISSUE THREAD

**Issue by paul58914080** [mjeanroy/bower-npm-resolver#57]
I am trying to install angular with (please note I am have a private npm registry i.e. the organization's)

`bower install npm:angular --save`

I am getting the following exception

```
Stack trace:
NestedError: Could not require module 'npm'
    at requireg (C:\Users\paul\nodist\bin\node_modules\bower-npm-resolver\node_modules\requireg\lib\requireg.js:14:11)
    at Object.<anonymous> (C:\Users\paul\nodist\bin\node_modules\bower-npm-resolver\dist\npm-utils.js:35:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\paul\nodist\bin\node_modules\bower-npm-resolver\dist\resolver.js:34:16)
Caused By: AssertionError: missing path
    at Module.require (module.js:496:3)
    at require (internal/module.js:20:19)
    at requireg (C:\Users\paul\nodist\bin\node_modules\bower-npm-resolver\node_modules\requireg\lib\requireg.js:12:12)
    at Object.<anonymous> (C:\Users\paul\nodist\bin\node_modules\bower-npm-resolver\dist\npm-utils.js:35:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

Console trace:
Error
    at StandardRenderer.error (C:\Users\paul\nodist\bin\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\paul\nodist\bin\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (C:\Users\paul\nodist\bin\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\paul\nodist\bin\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\paul\nodist\bin\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\paulnodist\bin\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\paul\nodist\bin\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\paul\nodist\bin\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.8.2
Node version: 7.2.1
OS: Windows_NT 6.1.7601 ia32
```

I have the following in .bowerrc

```
{
  "resolvers": [
    "bower-npm-resolver"
  ]
}
```

**Comment by mjeanroy** [comment]
That's weird.
What is your `NODE_PATH` environment variable?
How did you install node? With `nvm`?

**Comment by FLGMwt** [comment]
I'm also having this issue. I don't have a `NODE_PATH` var and I installed node w/ homebrew

I tried with bower 1.8.0 and 1.8.2 (latest). my bowerrc is project-local. I tried with global and local bower installs and got the same error.

node: 7.10.0
npm: 4.2.0
bower: 1.8.2
OS: Darwin 16.7.0 x64

**Comment by FLGMwt** [comment]
ah, did some investigation, bower-npm-resolver expects `NODE_PATH`. I'm guessing the npm brew doesn't configure this, but it should point to the global npm install's modules directory. For me this  was  `/usr/local/lib/node_modules` so the following fixed this:

```
 export NODE_PATH=/usr/local/lib/node_modules
```

**Comment by bzmw** [comment]
Is there a fix coming for this issue for those of us who installed `node` through `brew`

**Comment by mjeanroy** [comment]
Hi @bzmw,

The problem seems to be with `requireg` module (`bower-npm-resolver` use that to require the `npm` module). Maybe we can fix it in `bower-npm-resolver`, but I think it is worth to open an issue in  `requireg` repository to explain the problem.

Since I don't use brew, I probably won't be able to fix it myself, but any PR with a good workaround is welcome :)

**Comment by mjeanroy** [comment]
Closing this issue as this is not a problem with `bower-npm-resolver` but with `requireg` (with a workaround suggested in associated issue).

**Comment by rohitm62** [comment]
Hello Everyone , 
Recently I have encountered similar issue with npm , sharing the error logs if some one can help .

(node:31192) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[16:00:28] Using gulpfile C:\Rohit_WorkSpace\DSA\Source_Code\SAL\ec-quikr-components-bower\gulpfile.js
[16:00:28] Starting 'bowerInstall'...
NestedError: Could not require module 'npm'
[16:00:29] Finished 'bowerInstall' after 615 ms
----------------------------- End bower install --------------------------
----------------------------- Before_bower component --------------------------
Directory Path - C:\Rohit_WorkSpace\DSA\Source_Code\sal\ec-quikr-components-bower\components\sal-fund-report\bower_components
Error: ENOENT: no such file or directory, scandir 'C:\Rohit_WorkSpace\DSA\Source_Code\sal\ec-quikr-components-bower\components\sal-fund-report\bower_components'
    at Object.readdirSync (node:fs:1584:26)
    at Object.<anonymous> (C:\Rohit_WorkSpace\DSA\Source_Code\sal\ec-quikr-components-bower\execInstall.js:145:29)
    at Module._compile (node:internal/modules/cjs/loader:1730:14)
    at Object..js (node:internal/modules/cjs/loader:1895:10)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Rohit_WorkSpace\\DSA\\Source_Code\\sal\\ec-quikr-components-bower\\components\\sal-fund-report\\bower_components'
}
